import { build, transform } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));

// Keep the release self-contained so file://, downloads and static hosting work.
export async function buildHTML() {
  const [bundle, template, css, pkg] = await Promise.all([
    build({
      absWorkingDir: root,
      entryPoints: ["src/main.js"],
      bundle: true,
      format: "iife",
      target: "es2020",
      write: false,
      legalComments: "none",
    }),
    readFile(resolve(root, "src/index.html"), "utf8"),
    readFile(resolve(root, "src/styles.css"), "utf8"),
    readFile(resolve(root, "package.json"), "utf8"),
  ]);
  const style = await transform(css, { loader: "css", minify: true });
  const js = bundle.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
  const html = template
    .replace(
      '<link rel="stylesheet" href="./styles.css" />',
      () => `<style>\n${style.code}</style>`,
    )
    .replace(
      '<script type="module" src="./main.js"></script>',
      () => `<script>\n${js}</script>`,
    );
  if (html === template || /src="\.\/main.js"|href="\.\/styles.css"/.test(html))
    throw new Error(
      "Source template must contain the expected stylesheet and module tags.",
    );
  return html.replace(
    "<!doctype html>",
    `<!doctype html>\n<!-- Springheel ${JSON.parse(pkg).version}. Generated by npm run build; edit src/ instead. -->`,
  );
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const output = await buildHTML();
  if (process.argv.includes("--check")) {
    const existing = await readFile(resolve(root, "index.html"), "utf8");
    if (existing !== output)
      throw new Error("index.html is stale. Run npm run build and commit it.");
    console.log("Standalone HTML matches source.");
  } else {
    await writeFile(resolve(root, "index.html"), output);
    console.log(`Built index.html (${Buffer.byteLength(output)} bytes).`);
  }
}
